Repository Hrr-HabbitRoutineResult/Hrr_FE, pull requests merged in 2025-02, with the labels that each got.

#48 Feat: 이메일 인증코드 전송 및 확인 API 연동 #46
  app/build.gradle.kts
  app/src/main/java/com/example/hrr_android/access/AuthViewModel.kt
  app/src/main/java/com/example/hrr_android/access/model/EmailConfirmRequest.kt
  app/src/main/java/com/example/hrr_android/access/model/EmailConfirmResponse.kt
  app/src/main/java/com/example/hrr_android/access/model/EmailVerificationRequest.kt
  app/src/main/java/com/example/hrr_android/access/model/EmailVerificationResponse.kt
  app/src/main/java/com/example/hrr_android/access/network/AuthService.kt
  app/src/main/java/com/example/hrr_android/access/repository/AuthRepository.kt
  app/src/main/java/com/example/hrr_android/access/ui/fragment/InfoInputFragment.kt
  app/src/main/res/layout/fragment_info_input.xml
  gradle/libs.versions.toml
Labels: feature

#31 Feat: 게시판 관련 화면 UI 구현 #30
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hrr_android/CommunityFragment.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/java/com/example/hrr_android/community/adapter/CommunityRVAdapter.kt
  app/src/main/java/com/example/hrr_android/community/adapter/PostRVAdapter.kt
  app/src/main/java/com/example/hrr_android/community/model/BaseCommiunity.kt
  app/src/main/java/com/example/hrr_android/community/model/Community.kt
  app/src/main/java/com/example/hrr_android/community/model/Post.kt
  app/src/main/java/com/example/hrr_android/community/ui/BoardActivity.kt
  app/src/main/java/com/example/hrr_android/community/ui/fragment/CommunityContentFragment.kt
  app/src/main/java/com/example/hrr_android/community/ui/fragment/CommunityFragment.kt
  app/src/main/java/com/example/hrr_android/community/ui/fragment/CommunityTabContentFragment.kt
  app/src/main/res/drawable/bg_grey_50_filled_30.xml
  app/src/main/res/drawable/bg_grey_50_filled_5.xml
  app/src/main/res/drawable/btn_floating_more.xml
  app/src/main/res/drawable/btn_floating_post.xml
  app/src/main/res/drawable/ic_community_arrow_down.xml
  app/src/main/res/drawable/ic_community_arrow_up.xml
  app/src/main/res/drawable/ic_community_comment.xml
  app/src/main/res/drawable/ic_community_hot.xml
  app/src/main/res/drawable/ic_community_my_post.xml
  app/src/main/res/drawable/ic_community_new.xml
  app/src/main/res/drawable/ic_community_pin_selected.xml
  app/src/main/res/drawable/ic_community_pin_unselected.xml
  app/src/main/res/drawable/ic_community_saved.xml
  app/src/main/res/drawable/ic_post_like_color.xml
  app/src/main/res/drawable/ic_post_list_comment.xml
  app/src/main/res/drawable/ic_post_list_like.xml
  app/src/main/res/drawable/ic_search_black.xml
  app/src/main/res/layout/activity_board.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_community_content.xml
  app/src/main/res/layout/fragment_community_tab_content.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/layout/item_post_list.xml
  app/src/main/res/layout/layout_board_hot_post.xml
Labels: feature

#47 Feat: 프로필 화면에 있는 설정 기능 구현
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/SettingFragment.kt
  app/src/main/res/drawable/toggle_bg.xml
  app/src/main/res/drawable/toggle_thumb.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#51 Feat: 회원가입 API 연동 #50
  app/build.gradle.kts
  app/src/main/java/com/example/hrr_android/access/AuthViewModel.kt
  app/src/main/java/com/example/hrr_android/access/model/RegisterRequest.kt
  app/src/main/java/com/example/hrr_android/access/model/RegisterResponse.kt
  app/src/main/java/com/example/hrr_android/access/network/AuthService.kt
  app/src/main/java/com/example/hrr_android/access/repository/AuthRepository.kt
  app/src/main/java/com/example/hrr_android/access/ui/fragment/InfoInputFragment.kt
  gradle/libs.versions.toml
Labels: feature

#39 Feat: 사용자 맞춤 추천 화면의 버튼 활성화/비활성화 기능 추가 #36
  app/src/main/java/com/example/hrr_android/onboarding/OnboardingStep.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/OnboardingActivity.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/fragment/CategoryFragment.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/fragment/GoalFragment.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/fragment/InfoSelectFragment.kt
  app/src/main/java/com/example/hrr_android/onboarding/utils/RadioGroupUtils.kt
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_onboarding.xml
Labels: feature, refactor

#33 Feat: 레벨 로드맵-프로필 화면 연결 및 레벨업 프로세스 구현
  app/src/main/java/com/example/hrr_android/LevelDialog.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileLevelFragment.kt
  app/src/main/res/drawable/bg_level_bronze.xml
  app/src/main/res/drawable/bg_level_challenger.xml
  app/src/main/res/drawable/bg_level_gold.xml
  app/src/main/res/drawable/bg_level_master.xml
  app/src/main/res/drawable/bg_level_silver.xml
  app/src/main/res/drawable/bg_radius30_main_active.xml
  app/src/main/res/drawable/bg_radius30_sub06.xml
  app/src/main/res/drawable/ic_level_achieved.xml
  app/src/main/res/drawable/ic_level_default.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_level_get.xml
  app/src/main/res/layout/fragment_profile_level.xml
Labels: feature

#60 Refactor: Bottom Navi에 Naviagtion Component 방식 추가 #59
  app/build.gradle.kts
  app/src/main/java/com/example/hrr_android/HomeFragment.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/nav_graph.xml
  gradle/libs.versions.toml
Labels: feature, refactor

#43 Feat: 프로필 팔로우 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hrr_android/Follow.kt
  app/src/main/java/com/example/hrr_android/FollowRVAdapter.kt
  app/src/main/java/com/example/hrr_android/FollowVPAdapter.kt
  app/src/main/java/com/example/hrr_android/FollowerFragment.kt
  app/src/main/java/com/example/hrr_android/FollowingFragment.kt
  app/src/main/java/com/example/hrr_android/OtherProfileActivity.kt
  app/src/main/java/com/example/hrr_android/ProfileCommon.kt
  app/src/main/java/com/example/hrr_android/ProfileFollowFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileVPAdapter.kt
  app/src/main/res/drawable/bg_radius10_white_border1_grey500.xml
  app/src/main/res/drawable/btn_message.xml
  app/src/main/res/drawable/btn_more_dot.xml
  app/src/main/res/drawable/btn_profile_follow.xml
  app/src/main/res/drawable/btn_profile_following.xml
  app/src/main/res/drawable/ic_folloing.xml
  app/src/main/res/drawable/ic_follow.xml
  app/src/main/res/drawable/ic_profile_default.png
  app/src/main/res/drawable/ic_profile_default.xml
  app/src/main/res/layout/activity_other_profile.xml
  app/src/main/res/layout/dialog_bottom_sheet.xml
  app/src/main/res/layout/fragment_follower.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profile_follow.xml
  app/src/main/res/layout/item_profile_follow.xml
  app/src/main/res/values/styles.xml
Labels: feature

#45 Feat: 인기글 섹션 및 알림 화면 UI 구현 #44
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hrr_android/HomeFragment.kt
  app/src/main/java/com/example/hrr_android/HotPost.kt
  app/src/main/java/com/example/hrr_android/HotPostRVAdapter.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/java/com/example/hrr_android/Notification.kt
  app/src/main/java/com/example/hrr_android/NotificationActivity.kt
  app/src/main/java/com/example/hrr_android/NotificationRVAdapter.kt
  app/src/main/java/com/example/hrr_android/NotificationType.kt
  app/src/main/java/com/example/hrr_android/TimeLeft.kt
  app/src/main/res/drawable/bg_square_grey_filled_15.xml
  app/src/main/res/drawable/ic_notification_badge.xml
  app/src/main/res/drawable/ic_notification_follow.xml
  app/src/main/res/drawable/ic_notification_profile.xml
  app/src/main/res/drawable/ic_notification_warning.xml
  app/src/main/res/drawable/img_character_grey.xml
  app/src/main/res/drawable/img_notification_none.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_hot_post_list.xml
  app/src/main/res/layout/item_notification_list.xml
Labels: feature

#54 Feat: 챌린지 인증 현황 화면 UI 구현 #25
  app/src/main/java/com/example/hrr_android/challenge/model/ChallengeType.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/common/decoration/DividerItemDecoration.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/common/decoration/GridSpaceItemDecoration.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/detail/ChallengeDialog.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/detail/ChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/ProgressFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/RecordFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/adapter/RecordPhotoAdapter.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/adapter/RecordTextAdapter.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/progress/ChallengersProgressFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/progress/MyProgressFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/progress/adapter/ProgressViewPagerAdapter.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/progress/calendar/CalendarFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/record/progress/calendar/CustomCalendarView.kt
  app/src/main/res/drawable/bg_button_selected_filled.xml
  app/src/main/res/drawable/bg_button_selected_stroke.xml
  app/src/main/res/drawable/bg_button_unselected_stroke.xml
  app/src/main/res/drawable/bg_calendar_selected_filled.xml
  app/src/main/res/drawable/bg_calendar_selected_stroke.xml
  app/src/main/res/drawable/bg_inner_circle.xml
  app/src/main/res/drawable/bg_radius_15_white.xml
  app/src/main/res/drawable/btn_refresh_floating.xml
  app/src/main/res/drawable/divider_line_1dp.xml
  app/src/main/res/drawable/ic_calendar_arrow_left.xml
  app/src/main/res/drawable/ic_calendar_arrow_right.xml
  app/src/main/res/drawable/ic_calendar_black.xml
  app/src/main/res/drawable/ic_progress_flag.xml
  app/src/main/res/drawable/ic_record_link.xml
  app/src/main/res/drawable/img_challenge_complete.xml
  app/src/main/res/drawable/img_record_text_thumbnail.png
  app/src/main/res/drawable/pb_my_challenge.xml
  app/src/main/res/layout/dialog_challenge.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_challengers_progress.xml
  app/src/main/res/layout/fragment_my_progress.xml
  app/src/main/res/layout/fragment_progress.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_record_photo.xml
  app/src/main/res/layout/item_record_text.xml
  app/src/main/res/layout/layout_challenge_button_complete.xml
  app/src/main/res/layout/layout_challenge_complete.xml
  app/src/main/res/layout/layout_challenge_weekly_certification.xml
  app/src/main/res/layout/layout_challengers_overview.xml
  app/src/main/res/layout/layout_challengers_progress.xml
  app/src/main/res/layout/layout_record_header.xml
  app/src/main/res/layout/layout_record_list.xml
  app/src/main/res/layout/layout_record_profile.xml
  app/src/main/res/layout/view_calendar.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/styles.xml
Labels: feature

#53 Feat: 쪽지 화면 UI 구현 #52
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hrr_android/DefaultDialog.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/java/com/example/hrr_android/MessageFragment.kt
  app/src/main/java/com/example/hrr_android/message/adapter/ChatroomRVAdapter.kt
  app/src/main/java/com/example/hrr_android/message/adapter/MessageListRVAdapter.kt
  app/src/main/java/com/example/hrr_android/message/model/ChatMessage.kt
  app/src/main/java/com/example/hrr_android/message/model/MessageList.kt
  app/src/main/java/com/example/hrr_android/message/ui/MessageChatroomActivity.kt
  app/src/main/java/com/example/hrr_android/message/ui/MessageFragment.kt
  app/src/main/res/drawable/bg_dialog_default.xml
  app/src/main/res/drawable/bg_message.xml
  app/src/main/res/drawable/bg_message_other.xml
  app/src/main/res/drawable/bg_message_search.xml
  app/src/main/res/drawable/btn_close_black.xml
  app/src/main/res/drawable/btn_message_bottom_30.xml
  app/src/main/res/drawable/ic_message_alarm.xml
  app/src/main/res/drawable/ic_message_bottom_block.xml
  app/src/main/res/drawable/ic_message_bottom_exit.xml
  app/src/main/res/drawable/ic_message_chat_arrow.xml
  app/src/main/res/drawable/ic_message_chat_more.xml
  app/src/main/res/drawable/ic_message_notification.xml
  app/src/main/res/drawable/ic_message_profile_default.xml
  app/src/main/res/drawable/ic_message_search.xml
  app/src/main/res/layout/activity_message_chatroom.xml
  app/src/main/res/layout/bottom_sheet_message.xml
  app/src/main/res/layout/dialog_default.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_message_list.xml
  app/src/main/res/layout/item_message_other.xml
Labels: feature

#57 Feat: 프로필 화면 수정 기능 구현 #49
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hrr_android/Badge.kt
  app/src/main/java/com/example/hrr_android/EditBadgeRVAdapter.kt
  app/src/main/java/com/example/hrr_android/EditProfileActivity.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/User.kt
  app/src/main/res/drawable/bg_circle_overlay.xml
  app/src/main/res/drawable/bg_radius10_white_border1_grey500.xml
  app/src/main/res/drawable/btn_edit_camera.xml
  app/src/main/res/drawable/btn_pen_edit.xml
  app/src/main/res/drawable/ic_badge_selected.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/dialog_profile_edit.xml
  app/src/main/res/layout/item_badge_edit.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/file_paths.xml
  gradle/libs.versions.toml
Labels: feature

#68 Bug: merge로 인해 생긴 자잘한 오류 수정
  app/src/main/java/com/example/hrr_android/HomeFragment.kt
  app/src/main/java/com/example/hrr_android/MyApplication.kt
  app/src/main/java/com/example/hrr_android/ProfileBadgeMoreFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileBadgeMoreRVAdapter.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/access/AuthViewModel.kt
  app/src/main/java/com/example/hrr_android/access/network/AuthService.kt
  app/src/main/java/com/example/hrr_android/access/repository/AuthRepository.kt
  app/src/main/java/com/example/hrr_android/access/ui/SignUpActivity.kt
  app/src/main/java/com/example/hrr_android/access/ui/fragment/InfoInputFragment.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/styles.xml
Labels: bug

#70 Feat: 오늘의 인기 챌린지 UI 구현
  app/src/main/java/com/example/hrr_android/ChallengeToday.kt
  app/src/main/java/com/example/hrr_android/ChallengeTodayVPAdapter.kt
  app/src/main/java/com/example/hrr_android/HomeFragment.kt
  app/src/main/java/com/example/hrr_android/HorizontalMarginItemDecoration.kt
  app/src/main/res/drawable/ic_app_slogan.xml
  app/src/main/res/drawable/ic_challenge_today_company.xml
  app/src/main/res/drawable/ic_challenge_today_health.xml
  app/src/main/res/drawable/ic_challenge_today_hobby.xml
  app/src/main/res/drawable/ic_challenge_today_learn.xml
  app/src/main/res/drawable/ic_challenge_today_routine.xml
  app/src/main/res/drawable/img_home_character.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_challenge_card_default.xml
  app/src/main/res/layout/item_challenge_card_new.xml
  app/src/main/res/layout/item_challenge_today.xml
Labels: feature, refactor

#71 Refactor: UI 및 PR 리뷰 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hrr_android/EditProfileActivity.kt
  app/src/main/java/com/example/hrr_android/LevelActivity.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/java/com/example/hrr_android/OtherProfileActivity.kt
  app/src/main/java/com/example/hrr_android/ProfileBadgeFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileBadgeMoreRVAdapter.kt
  app/src/main/java/com/example/hrr_android/ProfileCertificationRecordFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileCommon.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileMoreActivity.kt
  app/src/main/java/com/example/hrr_android/UserResponse.kt
  app/src/main/res/drawable/btn_arrow_left.png
  app/src/main/res/drawable/btn_arrow_left.xml
  app/src/main/res/drawable/btn_profile_menu.png
  app/src/main/res/drawable/btn_profile_menu.xml
  app/src/main/res/drawable/btn_rank_more.xml
  app/src/main/res/drawable/btn_setting_more.png
  app/src/main/res/drawable/btn_x.png
  app/src/main/res/drawable/btn_x.xml
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_profile_no_data.png
  app/src/main/res/drawable/ic_profile_no_data.xml
  app/src/main/res/drawable/img_badge_challenge_01.png
  app/src/main/res/drawable/img_badge_health_03.png
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_level.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_other_profile.xml
  app/src/main/res/layout/activity_profile_more.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profile_badge.xml
  app/src/main/res/layout/fragment_profile_certification_record.xml
  app/src/main/res/layout/fragment_profile_challenge.xml
  app/src/main/res/layout/fragment_profile_level.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_badge_edit.xml
  app/src/main/res/layout/item_profile_badge.xml
  app/src/main/res/layout/item_profile_completed_challenge.xml
  app/src/main/res/layout/item_profile_participating_challenge.xml
Labels: refactor

#77 Feat: 로그인 시 userId 저장 #76
  app/src/main/java/com/example/hrr_android/access/model/LoginResponse.kt
  app/src/main/java/com/example/hrr_android/access/repository/AuthRepository.kt
Labels: feature

#78 Feat: 토큰 갱신 API 연동 #63
  app/src/main/java/com/example/hrr_android/AuthInterceptor.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/java/com/example/hrr_android/NetworkModule.kt
  app/src/main/java/com/example/hrr_android/access/AuthEventManager.kt
  app/src/main/java/com/example/hrr_android/access/AuthViewModel.kt
  app/src/main/java/com/example/hrr_android/access/SingleLiveEvent.kt
  app/src/main/java/com/example/hrr_android/access/TokenManager.kt
  app/src/main/java/com/example/hrr_android/access/model/TokenRequest.kt
  app/src/main/java/com/example/hrr_android/access/model/TokenResponse.kt
  app/src/main/java/com/example/hrr_android/access/network/AuthService.kt
  app/src/main/java/com/example/hrr_android/access/repository/AuthRepository.kt
  app/src/main/java/com/example/hrr_android/access/ui/LoginActivity.kt
  app/src/main/java/com/example/hrr_android/access/ui/fragment/CompleteFragment.kt
Labels: feature

#79 Feat: 인증기록 api 연동 및 로그아웃 #73
  app/src/main/java/com/example/hrr_android/AuthInterceptor.kt
  app/src/main/java/com/example/hrr_android/HistoryResponse.kt
  app/src/main/java/com/example/hrr_android/ProfileCertificationRecordFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileMoreActivity.kt
  app/src/main/java/com/example/hrr_android/ProfileRecordMoreFragment.kt
  app/src/main/java/com/example/hrr_android/SettingFragment.kt
  app/src/main/java/com/example/hrr_android/SplashActivity.kt
  app/src/main/java/com/example/hrr_android/UserRepository.kt
  app/src/main/java/com/example/hrr_android/UserSevice.kt
  app/src/main/java/com/example/hrr_android/UserViewModel.kt
  app/src/main/java/com/example/hrr_android/access/model/LoginResponse.kt
  app/src/main/java/com/example/hrr_android/access/repository/AuthRepository.kt
  app/src/main/java/com/example/hrr_android/access/ui/LoginActivity.kt
  app/src/main/res/layout/fragment_setting.xml
Labels: feature

#81 Feat: 참가 중인 챌린지 API 연동 #75
  app/src/main/java/com/example/hrr_android/ChallengeCardVPAdapter.kt
  app/src/main/java/com/example/hrr_android/ChallengesOngoingResponse.kt
  app/src/main/java/com/example/hrr_android/HomeFragment.kt
  app/src/main/java/com/example/hrr_android/UserRepository.kt
  app/src/main/java/com/example/hrr_android/UserSevice.kt
  app/src/main/java/com/example/hrr_android/UserViewModel.kt
  app/src/main/res/layout/item_challenge_card_default.xml
Labels: feature

#84 Feat: 챌린지(참가중인, 최근 완주한) api 연동 #82
  app/src/main/java/com/example/hrr_android/ChallengeEndResponse.kt
  app/src/main/java/com/example/hrr_android/ProfileChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileChallengeMoreFragment.kt
  app/src/main/java/com/example/hrr_android/UserRepository.kt
  app/src/main/java/com/example/hrr_android/UserSevice.kt
  app/src/main/java/com/example/hrr_android/UserViewModel.kt
  app/src/main/java/com/example/hrr_android/access/ValidUtils.kt
Labels: feature

#90 Feat: 팔로우 관련 api 연결
  app/src/main/java/com/example/hrr_android/BlockResponse.kt
  app/src/main/java/com/example/hrr_android/Follow.kt
  app/src/main/java/com/example/hrr_android/FollowRVAdapter.kt
  app/src/main/java/com/example/hrr_android/FollowResponse.kt
  app/src/main/java/com/example/hrr_android/FollowResult.kt
  app/src/main/java/com/example/hrr_android/FollowVPAdapter.kt
  app/src/main/java/com/example/hrr_android/FollowerFragment.kt
  app/src/main/java/com/example/hrr_android/FollowingFragment.kt
  app/src/main/java/com/example/hrr_android/OtherProfileActivity.kt
  app/src/main/java/com/example/hrr_android/OtherUserViewModel.kt
  app/src/main/java/com/example/hrr_android/ProfileChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileChallengeMoreFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileCommon.kt
  app/src/main/java/com/example/hrr_android/ProfileFollowFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileMoreActivity.kt
  app/src/main/java/com/example/hrr_android/ProfileVPAdapter.kt
  app/src/main/java/com/example/hrr_android/UserRepository.kt
  app/src/main/java/com/example/hrr_android/UserSevice.kt
  app/src/main/java/com/example/hrr_android/UserViewModel.kt
  app/src/main/res/layout/fragment_profile.xml
Labels: feature

#93 Bug: Refresh Token 만료 시 로그아웃 안 되는 문제 해결
  app/src/main/java/com/example/hrr_android/AuthInterceptor.kt
Labels: bug

#95 Feat: 챌린지 인증(글) UI 구현 #56
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/base/BaseCertificationFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/draft/DraftListFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/draft/adapter/DraftListAdapter.kt
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/draft/adapter/DraftViewHolder.kt
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/draft/model/Draft.kt
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/post/PostFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/post/adapter/CommentAdapter.kt
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/post/model/Comment.kt
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/text/TextCertificationFragment.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/common/decoration/CenterDividerItemDecoration.kt
  app/src/main/res/drawable/bg_radius10_grey50.xml
  app/src/main/res/drawable/bg_radius15.xml
  app/src/main/res/drawable/bg_radius15_grey50.xml
  app/src/main/res/drawable/btn_more_dot_black.xml
  app/src/main/res/drawable/ic_certification_gallery.xml
  app/src/main/res/drawable/ic_certification_link.xml
  app/src/main/res/drawable/ic_comment_adopt.xml
  app/src/main/res/drawable/ic_comment_like.xml
  app/src/main/res/drawable/ic_comment_more.xml
  app/src/main/res/drawable/ic_comment_reply.xml
  app/src/main/res/drawable/ic_locked.xml
  app/src/main/res/drawable/ic_post_bookmark.xml
  app/src/main/res/drawable/ic_post_comment.xml
  app/src/main/res/drawable/ic_post_like.xml
  app/src/main/res/drawable/ic_post_link.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/drawable/ic_unlocked.xml
  app/src/main/res/layout/dialog_comment_more.xml
  app/src/main/res/layout/dialog_link_input.xml
  app/src/main/res/layout/fragment_draft_list.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/fragment_text_certification.xml
  app/src/main/res/layout/item_certification_draft.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/layout_comment_input.xml
  app/src/main/res/layout/layout_post_buttons.xml
  app/src/main/res/layout/layout_post_profile.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#102 Feat: 사용자 맞춤 추천 API 연동
  app/build.gradle.kts
  app/src/main/java/com/example/hrr_android/LoadingActivity.kt
  app/src/main/java/com/example/hrr_android/UserRepository.kt
  app/src/main/java/com/example/hrr_android/UserSevice.kt
  app/src/main/java/com/example/hrr_android/UserViewModel.kt
  app/src/main/java/com/example/hrr_android/onboarding/adapter/OnboardingVPAdapter.kt
  app/src/main/java/com/example/hrr_android/onboarding/model/OnboardingRequest.kt
  app/src/main/java/com/example/hrr_android/onboarding/model/OnboardingResponse.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/OnboardingActivity.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/ResultActivity.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/fragment/CategoryFragment.kt
  app/src/main/java/com/example/hrr_android/onboarding/utils/RadioGroupUtils.kt
  app/src/main/res/layout/activity_result.xml
  app/src/main/res/layout/item_challenge_onboarding.xml
Labels: feature

#106 Feat: 화면전환 인터렉션 및 UI 개선
  app/src/main/java/com/example/hrr_android/ChallengeCardVPAdapter.kt
  app/src/main/java/com/example/hrr_android/ChallengeTodayVPAdapter.kt
  app/src/main/java/com/example/hrr_android/HomeFragment.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/java/com/example/hrr_android/NotificationActivity.kt
  app/src/main/java/com/example/hrr_android/OnChallengeClickListener.kt
  app/src/main/java/com/example/hrr_android/ProfileChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/access/model/RegisterResponse.kt
  app/src/main/java/com/example/hrr_android/access/ui/LoginActivity.kt
  app/src/main/java/com/example/hrr_android/access/ui/SignUpActivity.kt
  app/src/main/java/com/example/hrr_android/challenge/ui/detail/ChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/onboarding/adapter/OnboardingVPAdapter.kt
  app/src/main/java/com/example/hrr_android/onboarding/model/OnboardingResponse.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/IntroActivity.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/OnboardingActivity.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/ResultActivity.kt
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#111 Feat: 설정 UI 구현
  app/src/main/java/com/example/hrr_android/BlockRVAdapter.kt
  app/src/main/java/com/example/hrr_android/CommentedPostRVAdapter.kt
  app/src/main/java/com/example/hrr_android/Post.kt
  app/src/main/java/com/example/hrr_android/ProfileChallengerMoreRVAdapter.kt
  app/src/main/java/com/example/hrr_android/ProfileMoreActivity.kt
  app/src/main/java/com/example/hrr_android/QuitResponse.kt
  app/src/main/java/com/example/hrr_android/SettingAccountFragment.kt
  app/src/main/java/com/example/hrr_android/SettingBlockListFragment.kt
  app/src/main/java/com/example/hrr_android/SettingCommentChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/SettingFragment.kt
  app/src/main/java/com/example/hrr_android/SettingLikeChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/SettingNoticeFragment.kt
  app/src/main/java/com/example/hrr_android/SettingNoticeMoreFragment.kt
  app/src/main/java/com/example/hrr_android/SettingSaveChallengeFragment.kt
  app/src/main/java/com/example/hrr_android/TempUser.kt
  app/src/main/java/com/example/hrr_android/UserRepository.kt
  app/src/main/java/com/example/hrr_android/UserSevice.kt
  app/src/main/java/com/example/hrr_android/UserViewModel.kt
  app/src/main/java/com/example/hrr_android/makechallenge/MakeChallengeFragment.kt
  app/src/main/res/drawable/bg_top_radius10.xml
  app/src/main/res/drawable/ic_block.xml
  app/src/main/res/drawable/ic_blocked.xml
  app/src/main/res/layout/bottom_sheet_withdrawal.xml
  app/src/main/res/layout/dialog_block.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/fragment_make_challenge.xml
  app/src/main/res/layout/fragment_make_challenge_basic.xml
  app/src/main/res/layout/fragment_make_challenge_study.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/fragment_setting_account.xml
  app/src/main/res/layout/fragment_setting_block_list.xml
  app/src/main/res/layout/fragment_setting_comment_challenge.xml
  app/src/main/res/layout/fragment_setting_like_challenge.xml
  app/src/main/res/layout/fragment_setting_notice.xml
  app/src/main/res/layout/fragment_setting_notice_more.xml
  app/src/main/res/layout/fragment_setting_save_challenge.xml
  app/src/main/res/layout/item_block_list.xml
  app/src/main/res/layout/item_post_commented.xml
  app/src/main/res/layout/item_profile_challenge_more.xml
  app/src/main/res/layout/view_calendar.xml
Labels: feature

#112 Feat: 뱃지 api 연동
  app/src/main/java/com/example/hrr_android/AuthInterceptor.kt
  app/src/main/java/com/example/hrr_android/Badge.kt
  app/src/main/java/com/example/hrr_android/BadgeCondition.kt
  app/src/main/java/com/example/hrr_android/BadgeResponse.kt
  app/src/main/java/com/example/hrr_android/EditProfileActivity.kt
  app/src/main/java/com/example/hrr_android/MyBadgeDetailActivity.kt
  app/src/main/java/com/example/hrr_android/ProfileBadgeFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileBadgeMoreFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileCommon.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/ProfileUpdateRequest.kt
  app/src/main/java/com/example/hrr_android/ProfileUpdateResponse.kt
  app/src/main/java/com/example/hrr_android/RecentBadge.kt
  app/src/main/java/com/example/hrr_android/UserRepository.kt
  app/src/main/java/com/example/hrr_android/UserResponse.kt
  app/src/main/java/com/example/hrr_android/UserService.kt
  app/src/main/java/com/example/hrr_android/UserViewModel.kt
  app/src/main/res/layout/fragment_profile_badge_more.xml
Labels: feature

#105 Bug: 인증 사진 프리뷰 화질 개선 #104
  app/src/main/java/com/example/hrr_android/challenge/certification/ui/photo/PhotoCertificationFragment.kt
  app/src/main/res/layout/fragment_text_certification.xml
  app/src/main/res/layout/layout_photo_write.xml
Labels: bug, question

#122 Feat: UI 수정사항 반영 및 테스트 후 기능 보완
  app/src/main/java/com/example/hrr_android/BackPressUtils.kt
  app/src/main/java/com/example/hrr_android/ChallengeService.kt
  app/src/main/java/com/example/hrr_android/HomeFragment.kt
  app/src/main/java/com/example/hrr_android/MainActivity.kt
  app/src/main/java/com/example/hrr_android/OtherProfileActivity.kt
  app/src/main/java/com/example/hrr_android/ProfileFragment.kt
  app/src/main/java/com/example/hrr_android/SettingAccountFragment.kt
  app/src/main/java/com/example/hrr_android/UserResponse.kt
  app/src/main/java/com/example/hrr_android/access/network/AuthService.kt
  app/src/main/java/com/example/hrr_android/access/ui/LoginActivity.kt
  app/src/main/java/com/example/hrr_android/access/ui/PasswordActivity.kt
  app/src/main/java/com/example/hrr_android/onboarding/ui/ResultActivity.kt
  app/src/main/res/drawable/bg_kakao_login.xml
  app/src/main/res/drawable/ic_kakao_logo.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: feature
